Add ability to specify temperature unit via xres, and fallback to country locale if unspecified. Based on https://github.com/regolith-linux/regolith-desktop/issues/372.

diff --git a/scripts/weather b/scripts/weather
--- a/scripts/weather
+++ b/scripts/weather
@@ -26,14 +26,24 @@ VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}
 # Information on the various formats: https://github.com/chubin/wttr.in
 VALUE_WEATHER_FORMAT=${weather_format:-$(xrescat i3xrocks.weather.format "1")}
 
+# Determine units to use for temperature
+WEATHER_UNITS=$(xrescat i3xrocks.weather.units)
+if [ -z "$WEATHER_UNITS" ]; then
+    COUNTRY=$(locale | grep LC_TIME | head -n1 | cut -d "=" -f 2 | cut -d "_" -f 2 | cut -d "." -f 1)
+    if [ "$COUNTRY" == "US" ]; then
+        WEATHER_UNITS="f"
+    else
+        WEATHER_UNITS="m"
+    fi
+fi
+
 # Defaults to IP address location
 IP_LOCATION="$(curl -s https://ipapi.co/city/),$(curl -s https://ipapi.co/region/)"
 VALUE_WEATHER_LOCATION=${weather_location:-$(xrescat i3xrocks.weather.location "$IP_LOCATION")}
 ENCODED_VALUE_WEATHER_LOCATION=$(urlencode "$VALUE_WEATHER_LOCATION")
 VALUE_WEATHER_ERROR_MESSAGE=${error_message:-$(xrescat i3xrocks.weather.error_message "")}
-
-WEATHER_DATA=$(curl -sS wttr.in/${ENCODED_VALUE_WEATHER_LOCATION}?format="${VALUE_WEATHER_FORMAT}" || echo "${VALUE_WEATHER_ERROR_MESSAGE}")
-
+echo "curl -sS wttr.in/${ENCODED_VALUE_WEATHER_LOCATION}?/${WEATHER_UNITS}&format=${VALUE_WEATHER_FORMAT}"
+WEATHER_DATA=$(curl -sS wttr.in/${ENCODED_VALUE_WEATHER_LOCATION}?/${WEATHER_UNITS}&format=${VALUE_WEATHER_FORMAT} || echo "${VALUE_WEATHER_ERROR_MESSAGE}")
 echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">${WEATHER_DATA}</span>"
 
 if [ ! -z "$button" ]; then
