Make curl work for special characters
## Done

- Put curl for weather in double quotes as the `&format` wasn't being passed properly and returned multiple lines

## QA

- download this branch
- run `weather` from the command line
- see that the output is on one line

diff --git a/scripts/weather b/scripts/weather
--- a/scripts/weather
+++ b/scripts/weather
@@ -43,7 +43,7 @@ VALUE_WEATHER_LOCATION=${weather_location:-$(xrescat i3xrocks.weather.location "
 ENCODED_VALUE_WEATHER_LOCATION=$(urlencode "$VALUE_WEATHER_LOCATION")
 VALUE_WEATHER_ERROR_MESSAGE=${error_message:-$(xrescat i3xrocks.weather.error_message "")}
 echo "curl -sS wttr.in/${ENCODED_VALUE_WEATHER_LOCATION}?/${WEATHER_UNITS}&format=${VALUE_WEATHER_FORMAT}"
-WEATHER_DATA=$(curl -sS wttr.in/${ENCODED_VALUE_WEATHER_LOCATION}?/${WEATHER_UNITS}&format=${VALUE_WEATHER_FORMAT} || echo "${VALUE_WEATHER_ERROR_MESSAGE}")
+WEATHER_DATA=$(curl -sS "https://wttr.in/${ENCODED_VALUE_WEATHER_LOCATION}?/${WEATHER_UNITS}&format=${VALUE_WEATHER_FORMAT}" || echo "${VALUE_WEATHER_ERROR_MESSAGE}")
 echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">${WEATHER_DATA}</span>"
 
 if [ ! -z "$button" ]; then
