Using curl error code

diff --git a/scripts/weather b/scripts/weather
--- a/scripts/weather
+++ b/scripts/weather
@@ -9,17 +9,11 @@ VALUE_WEATHER_FORMAT=${weather_format:-$(xrescat i3xrocks.weather.format "1")}
 
 # Defaults to IP address location
 VALUE_WEATHER_LOCATION=${weather_location:-$(xrescat i3xrocks.weather.location "")}
+VALUE_WEATHER_ERROR_MESSAGE=${error_message:-$(xrescat i3xrocks.weather.error_message "")}
 
-WEATHER_ERROR_MESSAGE=${error_message:-$(xrescat i3xrocks.weather.error_message "")}
-WEATHER_DATA_FILE=/tmp/i3xrocks_weather_data
-RESPONSE_CODE=`curl -o ${WEATHER_DATA_FILE} -sS -w "%{http_code}" wttr.in/${VALUE_WEATHER_LOCATION}?format="${VALUE_WEATHER_FORMAT}"`
+WEATHER_DATA=$(curl -sS wttr.fin/${VALUE_WEATHER_LOCATION}?format="${VALUE_WEATHER_FORMAT}" || echo "${VALUE_WEATHER_ERROR_MESSAGE}")
 
-if [ $RESPONSE_CODE -ne "200" ]; then
-    echo "${WEATHER_ERROR_MESSAGE}"
-else
-    WEATHER_DATA=`cat ${WEATHER_DATA_FILE}`
-    echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">${WEATHER_DATA}</span>"
-fi
+echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">${WEATHER_DATA}</span>"
 
 if [ ! -z "$button" ]; then
     /usr/bin/i3-msg -q exec xdg-open https://wttr.in/${VALUE_WEATHER_LOCATION}
